### ISSUE TITLE
Support for seasonal forecasts

### ISSUE THREAD

**Issue by matteodefelice** [ecmwf/climetlab#13]
Do you plan to support also operations on C3S seasonal forecast data?

**Comment by floriankrb** [comment]
yes we do, it is already supported as we support the datasets in the Copernicus Data Store (CDS). 
There is a notebook in the documentation with an example of retrieving and plotting the "reanalysis-era5-single-levels" dataset.
 : https://climetlab.readthedocs.io/en/latest/examples/03-source-cds.html.

(In collaboration with the CDS team, it will also be possible to adapt this integration for some or all datasets in the CDS, as a plugin for climetlab.)
