### ISSUE TITLE
feature request: let user change cache folder

### ISSUE THREAD

**Issue by aaronspring** [ecmwf/climetlab#15]
we spoke about this in the S2S AI call on thursday. would it be possible to let the user set the location of the downloaded files? 
in case that location gets filled up? I thought it was `/tmp` but I cannot find the data there. I understand that the filesnames are hashed. its just that I dont want to spill a location on disk I cannot control.

**Comment by aaronspring** [comment]
as far as I can see you wrote the downloading and caching in `climetlab` from scratch: you could also see if you want to build on top of `intake` and `fsspec`. my usage example: https://renkulab.io/gitlab/aaron.spring/s2s-ai-competition-bootstrap/-/blob/master/notebooks/ECMWF_intake.ipynb
fsspec caching: https://filesystem-spec.readthedocs.io/en/latest/features.html#caching-files-locally

**Comment by b8raoult** [comment]
This already works, see https://climetlab.readthedocs.io/en/latest/reference/settings.html

**Comment by aaronspring** [comment]
great. thanks @b8raoult
