### ISSUE TITLE
allow xr.open_mfdataset(**kwargs)

### ISSUE THREAD

**Issue by aaronspring** [ecmwf/climetlab#16]
I would like to get more flexibility in how cached files are opened by xarray.

`cds.to_xarray(chunks={'longitude':'auto', 'step': 7})`

There seem to be many points where **kwargs could be supplied to.
Like here:
- https://github.com/ecmwf/climetlab/blob/78a4c98f35a49652f43145276be02fa9b4e0c31d/climetlab/sources/readers/directory.py#L36
- https://github.com/ecmwf/climetlab/blob/78a4c98f35a49652f43145276be02fa9b4e0c31d/climetlab/sources/readers/netcdf.py#L174
- https://github.com/ecmwf/climetlab/blob/78a4c98f35a49652f43145276be02fa9b4e0c31d/climetlab/sources/readers/netcdf.py#L263

I didnt open a PR yet, because there are so many occurrences of `xr.open_mfdataset` that we should discuss this first.

I hope to reduce the number of chunks and tasks in s2s-ai-competition datasets, by specifying `chunks={'step':7, 'forecast_time':53}`

**Comment by b8raoult** [comment]
This has now been fixed.

**Comment by aaronspring** [comment]
Thanks

**Comment by aaronspring** [comment]
I tried `cds.to_xarray(chunks={'forecast_time': 1})` to create smaller chunks upon reading in data, but there is no difference to `cds.to_xarray()`. Would it be possible to pass `open_mfdataset_kwargs` to `to_xarray()`? Another usecase could be to pass `decode_times` or other keywords
