### ISSUE TITLE
INFO Request is queued

### ISSUE THREAD

**Issue by gewitterblitz** [ecmwf/climetlab#28]
I am trying to access ERA5 data using both cdsapi and climetlab. Just replicating the example notebook here (https://climetlab.readthedocs.io/en/latest/examples/03-source-cds.html) on my laptop as well as provided binder link.

The code works fine to plot 2m temperature and mean sea level as shown in the example notebook. However, the moment I change one of the requested variables, the notebook code gets stuck indefinitely with the following message. 

```
source = cml.load_source(
    "cds",
    "reanalysis-era5-single-levels",
    variable=["2t", "blh"],
    product_type="reanalysis",
    area=[50, -50, 20, 50],
    date="2012-12-12",
    time="12:00",
    format="netcdf",
)
for s in source:
    cml.plot_map(s)

2021-10-25 19:31:26,858 INFO Lock 140013250624784 acquired on /tmp/climetlab-jovyan/cdsretriever-d1b901f874b7ac4e804d713920fc5c40fa5f10d2ca221b395896a72f6c9ca41b.nc.lock
2021-10-25 19:31:26,962 INFO Welcome to the CDS
2021-10-25 19:31:26,962 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-single-levels
2021-10-25 19:31:27,080 INFO Request is queued
```

The message above is from the binder notebook but I get the same result on my laptop as well.

**Comment by floriankrb** [comment]
I am not sure I follow you

AFAIK, the CDS API (https://cds.climate.copernicus.eu/api-how-to):
  import cdsapi
  c = cdsapi.Client()
would still download the data.

While using the toolbox, what I call the interactive CDS API (https://cds.climate.copernicus.eu/toolbox-editor/ , you need to register):
   import cdstoolbox as ct
    ...
would run only on the CDS machine and would not download data (to your local machine).
