### ISSUE TITLE
Directions for Contributors

### ISSUE THREAD

**Issue by emadehsan** [ecmwf/climetlab#29]
Hi @floriankrb , CliMetLab's documentation needs work and a new contributor can perhaps start by writing test-cases for new features too. What would be your advice for someone looking to contribute to CliMetLab? Where to start?

I'm passionate about working on Climate Change and CliMetLab seems like a perfect start. Pedro recommended CliMetLab to me.

**Comment by floriankrb** [comment]
Hi @emadehsan, yes you are most that welcome to contribute to climetlab. 

The documentation would be a good starting point. Perhaps you want to improve this part https://climetlab.readthedocs.io/en/latest/guide/sources.html by giving more details or add some example in https://climetlab.readthedocs.io/en/latest/guide/howtos.html.

Your feedback in setting up your dev environment would be also welcome, we would like contributors to be able to build the documentations and run the test without wasting time installing missing packages and fighting dependencies.

**Comment by emadehsan** [comment]
@floriankrb thanks so much! :)

I'll start from there

**Comment by emadehsan** [comment]
Hi @floriankrb , would appreciate your thoughts about the structure of [CliMetLab documentation](https://climetlab.readthedocs.io/en/latest/) and how it can possibly be improved

1. Having [`Developer Guide > Datasets`](https://climetlab.readthedocs.io/en/latest/developer/datasets.html) page when [`User Guide > Datasets`](https://climetlab.readthedocs.io/en/latest/guide/datasets.html) already exists would probably be redundant. Same can be said about [`Data sources`](https://climetlab.readthedocs.io/en/latest/developer/sources.html) page. Having a single `Datasets` page describing all the dataset related functionality (available to both `User` and `Developer`) might help maintain a single source of truth.

2. Also, I feel that having separate [`User Guide`](https://climetlab.readthedocs.io/en/latest/guide/overview.html),[`Contributor Guide`](https://climetlab.readthedocs.io/en/latest/contributing/overview.html) and [`Developer Guide`](https://climetlab.readthedocs.io/en/latest/developer/overview.html) could be a little confusing and sometimes repetitive?
I think that the hierarchy of the documentation would be much simpler and straight forward if it is organized with by `functionality` (e.g. `Plugin`, `Datasets`, `Data sources`) instead of `persona` (`User > Datasets`, `Developer > Data Sources`, `Contributor > Plugins`).

**Comment by emadehsan** [comment]
It's own issue https://github.com/ecmwf/climetlab/issues/31
