### ISSUE TITLE
Does climetlab replace cdsapi?

### ISSUE THREAD

**Issue by lgloege** [ecmwf/climetlab#3]
Thank you for making this package! This solves my biggest pain point with the cdsapi, the inability to load requested data into memory without saving to disk. Does ECMWF consider cdsapi deprecated and suggest using climetlab instead?

**Comment by b8raoult** [comment]
I am happy that you find this package useful. climetlab uses the cdsapi internally to access the CDS, so the cdsapi will not be deprecated. The data is still downloaded to disk, and then loaded in pandas and/or xarray. The aim of climetlab is to hide all that from the users, so they can focus on science more than coding. Please note that this package is still very new,  and features may be added/removed, until we reach version 1.0.
