### ISSUE TITLE
Loading CSV with Pandas in CML

### ISSUE THREAD

**Issue by mchantry** [ecmwf/climetlab#38]
If a csv with only one column of floats is loaded with CML to_pandas() then it interprets . as the separator. 
e.g. the file
```
soil_temperature
6.27001953125
5.779998779296875
6.1199951171875
6.010009765625
6.1400146484375

```
would be loaded as the following:
![Screenshot 2022-04-13 at 10 47 48](https://user-images.githubusercontent.com/14275475/163151078-fa4ff352-f097-4585-8b51-461f31f6e319.png)

**Comment by floriankrb** [comment]
fixed with version 0.11.6
