### ISSUE TITLE
Doing `pip install climetlab` does not install s3fs which is required to load zarr sources

### ISSUE THREAD

**Issue by jodemaey** [ecmwf/climetlab#45]
Trying to load zarr sources after a simple pip install gives me the following error:

```
          
E           File /opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/climetlab/sources/zarr.py:14
E                11 import os
E                12 from urllib.parse import urlparse
E           ---> 14 import s3fs
E                15 import xarray as xr
E                16 import zarr
E           
E           ModuleNotFoundError: No module named 's3fs'
E           ModuleNotFoundError: No module named 's3fs'
```

and I see that `s3fs` & `zarr` were removed from the `setup.py` file. Does it mean that climetlab is not supporting zarr at the moment?

**Comment by jodemaey** [comment]
I have added it in the requirements of my plugin. I guess this is the way to go, to let plugin developer choose if they want zarr support (if it is conflicting with other packages).

**Comment by floriankrb** [comment]
Yes, this is a good solution. 

Another solution would have been to set `climetlab[zarr]` as a dependency for your plugin. By adding the extra `[zarr]`, you would be asking climetlab to be installed with the required packages to make sure that zarr is working. This should be easier to maintain on your side : when a new package will be needed to read zarr, we will add it within climetlab and your plugin will not need any update.

**Comment by jodemaey** [comment]
Thanks, I will test this other solution for the next plugin release.
