### ISSUE TITLE
No module named 'climetlab.ml' when running cml.load_source

### ISSUE THREAD

**Issue by dodiyzw** [ecmwf/climetlab#49]
Hi there, 

I'm following along the MOOC course with ECMWF and I tried running the Jupyter notebook for the following line:

cml.load_source('file', 'test.grib')

I had a ModuleNotFoundError: No module named 'climetlab.ml'. I was running climetlab 0.13.10 (latest) and the same error occured both locally and on google collab.

Managed to get it running by downgrading it to climetlab-0.13.5. 

Is this a bug from the latest version? Posting here to follow along any developments :) 

Cheers.

**Comment by qinglonger** [comment]
```

import climetlab as cml
cml.load_source('file', 'test.grib')

```

need the **test.grib** in the folder that jupyter notebook run in .

**Comment by qinglonger** [comment]
If you have any question，you could send a email to me,my Email is songofsongs@vip.qq.com

**Comment by floriankrb** [comment]
this should be fixed with the more recent version of climetlab. Feel free to reopen if the same issue occurs.
