### ISSUE TITLE
Request for Enhanced Documentation on Diverse Data Retrieval in ClimetLab

### ISSUE THREAD

**Issue by daniloceano** [ecmwf/climetlab#57]
### What maintenance does this project need?

I am a PhD student in Atmospheric Sciences at the University of São Paulo. I recently discovered ClimetLab during the Machine Learning MOC by ECMWF and believe it has great potential for my research. However, I've encountered challenges due to the lack of detailed examples in the documentation, particularly regarding the retrieval of various data sources such as ERA5 pressure level data and ERA5 surface fluxes.

While the existing documentation provides a good starting point, it would be immensely beneficial for users like myself if it included more comprehensive examples and guidelines for accessing different types of datasets. Such enhancements would not only aid in research efficiency but also broaden the user base of ClimetLab within the atmospheric science community.

I appreciate your consideration of this request and look forward to any updates that could make ClimetLab even more user-friendly and versatile for researchers.

### Organisation

University of São Paulo - Institute of Astronomy, Geophysics and Atmospheric Sciences

**Comment by floriankrb** [comment]
Most of CliMetLab functionalities are being moved to another package called **earthkit.data**, which is under development. earthkit.data will be developed more and usable operationally. CliMetLab should then rely on earthkit.data to provide the same interface for the users (to be discussed).

There is/will be some work to do this transition. This is still under discussion, but the climetlab plugins could be supported by earthkit.data, or by climetlab. The decision could be different for dataset plugins and source plugins. Some of them could be included in one of the packages, or provided by another one.

In the meanwhile, related to climetlab maintenance and improving documentation, fixing the automatic generation of climetlab documentation could be an option (it is disabled as it was failing, see in the github actions).
